// AprendiendoVue/src/components/Slider.vue
<template>
      <div id="slider" class="slider-l">
           <h1>Bienvenido al cursor master de Javascript con REACT</h1>
           <a class="btn-go-blog" @click="redirigirToBlog()" >Ir al Blog</a>
         </div>
</template>
<script>

export default {
    name:'Slider',
    methods:{
      redirigirToBlog(){
        this.$router.push('/blg');
      }
    }
}
</script>

// InventarioAngular/src/app/components/slider/slider.component.ts
import { Component, Input, OnInit } from '@angular/core';

@Component({
  selector: 'app-slider',
  templateUrl: './slider.component.html',
  styleUrls: ['./slider.component.css']
})
export class SliderComponent implements OnInit {

  @Input() size: string;
  @Input() display: string;
  constructor() { }

  ngOnInit(): void {
  }

}

<div id="slider" class="slider-l" [ngClass]="{
    'slider-l' : !size || size == 'big',
    'slider-s' :  size == 'small' 
    }">
    
    <h1>Bienvenido al cursor master de Javascript con REACT</h1>
    <a href="./blog.html" class="btn-go-blog" >Ir al Blog</a>
</div>
