// InventarioAngular/src/app/components/sidebar/sidebar.component.ts
import { Component, OnInit } from '@angular/core';
import { Router, ActivatedRoute, Params} from '@angular/router';


@Component({
  selector: 'app-sidebar',
  templateUrl: './sidebar.component.html',
  styleUrls: ['./sidebar.component.css']
})
export class SidebarComponent implements OnInit {

  public searchstring: string;
  constructor(
    private _router: Router,
    private _activateR: ActivatedRoute
  ) { }

  ngOnInit(): void {
  }

  Search(){
    //console.log('Here!');
    if (this.searchstring || this.searchstring == '') {
      this._router.navigate(['/buscar/', this.searchstring])
    }
  }
}

<aside id="sidebar">
    <div id="nav-blog" class="sidebar-item">
      <h3>Puedes hacer esto</h3>
      <a [routerLink]="['/articulo-new']" class="btn-AddItem">Crear árticulo</a>
    </div>

    <div id="search" class="sidebar-item">
     <h3>Buscador</h3>
     <form #frmSidebar="ngForm" (ngSubmit)="Search()">
       <input type="text" name="search" id="inpsearch" [(ngModel)]="searchstring">
       <input type="submit" name="submit" id="btnBuscar" class="btn btn-find" value="Buscar">
     </form>
   </div>
  </aside>
  <div class="clearfix"></div>

// AprendiendoVue/src/components/Sidebar.vue
<template>
  <div>
    <aside id="sidebar">
      <div id="nav-blog" class="sidebar-item">
        <h3>Puedes hacer esto</h3>
        <a href="#" class="btn-AddItem">Crear árticulo</a>
      </div>

      <div id="search" class="sidebar-item">
        <h3>Buscador</h3>
        <form>
          <input type="text" name="search" id="inpsearch" />
          <input
            type="submit"
            name="submit"
            id="btnBuscar"
            class="btn btn-find"
            value="Buscar"
          />
        </form>
      </div>
    </aside>
 
  </div>
</template>
<script>
export default {
  name: "Sidebar",
  
};
</script>
